
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aumrudh Lal Kumar TJ
 */
public class addfee extends javax.swing.JFrame {

    /**
     * Creates new form addfee
     */
    public addfee() {
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        setPreferredSize(new Dimension(589, 439));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tpri = new javax.swing.JTextField();
        tcat = new javax.swing.JTextField();
        addcat = new javax.swing.JButton();
        home = new javax.swing.JButton();
        back = new javax.swing.JButton();
        month = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Fee");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Category");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 110, 110, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Months");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 170, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Price");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 230, 100, 35);

        tpri.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tpri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tpriKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tpriKeyTyped(evt);
            }
        });
        getContentPane().add(tpri);
        tpri.setBounds(260, 230, 220, 40);

        tcat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(tcat);
        tcat.setBounds(260, 110, 220, 40);

        addcat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addcat.setText("Add Category");
        addcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcatActionPerformed(evt);
            }
        });
        getContentPane().add(addcat);
        addcat.setBounds(88, 315, 180, 60);

        home.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home);
        home.setBounds(280, 315, 120, 60);

        back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(412, 315, 130, 60);

        month.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1 Month", "3 Months", "6 Months", "12 Months" }));
        month.setSelectedIndex(-1);
        getContentPane().add(month);
        month.setBounds(260, 170, 220, 40);

        jLabel17.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Add Fee ");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(230, 20, 140, 41);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aumrudh Lal Kumar TJ\\Documents\\NetBeansProjects\\gymautotmation\\images\\gym_backgrounds_001.jpg")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 590, 450);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcatActionPerformed
        // TODO add your handling code here:
        String s1=tcat.getText();
            
        String s2=(String)month.getSelectedItem();
        String ss3=tpri.getText();
        try{
            if(s1.equals("")){                
                    JOptionPane.showMessageDialog(null,"Enter Category","Alert",JOptionPane.WARNING_MESSAGE);     
            }
        else  if(month.getSelectedIndex() == -1){               
                    JOptionPane.showMessageDialog(null,"Enter Month","Alert",JOptionPane.WARNING_MESSAGE);     
            }
        else if(ss3.equals("")){                
                    JOptionPane.showMessageDialog(null,"Enter Price","Alert",JOptionPane.WARNING_MESSAGE);     
            }
        else {
            
        int s3=Integer.parseInt(tpri.getText());
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/gymautomationsystem","root","Jeyakumar28");
            Statement smt=conn.createStatement();
            smt.executeUpdate("INSERT INTO fee VALUES('"+s1+"','"+s2+"',"+s3+");");
            JOptionPane.showMessageDialog(null, "Inserted Sucssefully","Insertion", JOptionPane.INFORMATION_MESSAGE);
            tcat.setText("");
            month.setSelectedIndex(0);
            tpri.setText("");
           }
        }
        catch(Exception e1){
            System.out.print(e1);
        
        }
    }//GEN-LAST:event_addcatActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new adminhome().setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new fee().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void tpriKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpriKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tpriKeyTyped

    private void tpriKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpriKeyPressed
        // TODO add your handling code here:
        String a = tpri.getText();
        int length = a.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if(length<10){
                tpri.setEditable(true);
            }
            else{
                tpri.setEditable(false);
            }
        }
        else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                tpri.setEditable(true);
            }
            else{
                tpri.setEditable(false);
            }
        }        // TODO a
    }//GEN-LAST:event_tpriKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addfee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addfee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addfee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addfee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addfee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcat;
    private javax.swing.JButton back;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JTextField tcat;
    private javax.swing.JTextField tpri;
    // End of variables declaration//GEN-END:variables
}
