
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import javax.swing.*;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aumrudh Lal Kumar TJ
 */
public class addpdt extends javax.swing.JFrame {

    /**
     * Creates new form addpdt
     */
    public addpdt() {
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        setPreferredSize(new Dimension(400, 573));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        tquan = new javax.swing.JTextField();
        tprice = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        back = new javax.swing.JButton();
        tdesc = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Product");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 100, 63, 39);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quantity");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 160, 90, 38);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total Price");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 220, 110, 41);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Description");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 290, 120, 40);
        getContentPane().add(tname);
        tname.setBounds(170, 100, 180, 40);

        tquan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tquanKeyPressed(evt);
            }
        });
        getContentPane().add(tquan);
        tquan.setBounds(170, 160, 180, 40);

        tprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tpriceKeyPressed(evt);
            }
        });
        getContentPane().add(tprice);
        tprice.setBounds(170, 220, 180, 41);

        add.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(70, 360, 120, 50);

        back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(220, 360, 100, 50);
        getContentPane().add(tdesc);
        tdesc.setBounds(170, 290, 180, 40);

        jLabel18.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Add Product");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(120, 10, 180, 60);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aumrudh Lal Kumar TJ\\Documents\\NetBeansProjects\\gymautotmation\\images\\gym_backgrounds_001.jpg")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 400, 540);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
         new product().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
       
        String s1=tname.getText();    
        String s22=tquan.getText();         
        String ss3=tprice.getText();
           
        
        String s4=tdesc.getText();
        try{
            if(s1.equals("")){                
                    JOptionPane.showMessageDialog(null,"Enter Name","Alert",JOptionPane.WARNING_MESSAGE);     
            }
            else if(s22.equals("")){                
                    JOptionPane.showMessageDialog(null,"Enter Quanity","Alert",JOptionPane.WARNING_MESSAGE);     
            }
            else if(ss3.equals("")){                
                    JOptionPane.showMessageDialog(null,"Enter Price","Alert",JOptionPane.WARNING_MESSAGE);     
            }
                    else if(s4.equals("")){                
                    JOptionPane.showMessageDialog(null,"Enter Description","Alert",JOptionPane.WARNING_MESSAGE);     
            }
        else {
              int s2=Integer.parseInt(tquan.getText()); 
             int s3=Integer.parseInt(tprice.getText());
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/gymautomationsystem","root","Jeyakumar28");
            Statement smt=conn.createStatement();
            smt.executeUpdate("INSERT INTO product VALUES(NULL,'"+s1+"',"+s2+","+s3+",'"+s4+"');");
            JOptionPane.showMessageDialog(null, "Inserted Sucssefully","Insertion", JOptionPane.INFORMATION_MESSAGE);
            tname.setText("");
            tquan.setText("");
            tprice.setText("");
            tdesc.setText("");
        }
        }
        catch(Exception e1){
            System.out.print(e1);
            JOptionPane.showMessageDialog(null,"Enter valid Details","Alert",JOptionPane.WARNING_MESSAGE);    
        }
    }//GEN-LAST:event_addActionPerformed

    private void tquanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tquanKeyPressed
        // TODO add your handling code here:
        String a = tquan.getText();
        int length = a.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if(length<2){
                tquan.setEditable(true);
            }
            else{
                tquan.setEditable(false);
            }
        }
        else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                tquan.setEditable(true);
            }
            else{
                tquan.setEditable(false);
            }
        }  
    }//GEN-LAST:event_tquanKeyPressed

    private void tpriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpriceKeyPressed
        // TODO add your handling code here:
           String a = tprice.getText();
        int length = a.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if(length<10){
                tprice.setEditable(true);
            }
            else{
                tprice.setEditable(false);
            }
        }
        else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                tprice.setEditable(true);
            }
            else{
                tprice.setEditable(false);
            }
        }
    }//GEN-LAST:event_tpriceKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addpdt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addpdt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addpdt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addpdt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addpdt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tdesc;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tprice;
    private javax.swing.JTextField tquan;
    // End of variables declaration//GEN-END:variables
}
