
import java.awt.Dimension;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aumrudh Lal Kumar TJ
 */
public class adminhome extends javax.swing.JFrame {

    /**
     * Creates new form adminhome
     */
    public adminhome() {
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        setPreferredSize(new Dimension(630, 630));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        member = new javax.swing.JButton();
        Fee = new javax.swing.JButton();
        equipments = new javax.swing.JButton();
        account = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin HOmePage");
        getContentPane().setLayout(null);

        member.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        member.setText("Members");
        member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberActionPerformed(evt);
            }
        });
        getContentPane().add(member);
        member.setBounds(110, 275, 150, 40);

        Fee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Fee.setText("Fees");
        Fee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeeActionPerformed(evt);
            }
        });
        getContentPane().add(Fee);
        Fee.setBounds(380, 275, 140, 40);

        equipments.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        equipments.setText("Products");
        equipments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmentsActionPerformed(evt);
            }
        });
        getContentPane().add(equipments);
        equipments.setBounds(110, 509, 150, 40);

        account.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        account.setText("Account");
        account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountActionPerformed(evt);
            }
        });
        getContentPane().add(account);
        account.setBounds(370, 509, 160, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aumrudh Lal Kumar TJ\\Downloads\\OWN\\fee.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(380, 125, 140, 130);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aumrudh Lal Kumar TJ\\Downloads\\OWN\\cus.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 125, 150, 140);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aumrudh Lal Kumar TJ\\Downloads\\OWN\\ac1.jpg")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(380, 359, 150, 140);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aumrudh Lal Kumar TJ\\Downloads\\OWN\\equip.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 359, 150, 130);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("  Admin Panel ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(177, 37, 284, 49);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(500, 50, 100, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aumrudh Lal Kumar TJ\\Documents\\NetBeansProjects\\gymautotmation\\images\\gymback.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 640, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberActionPerformed
        // TODO add your handling code here:
       // this.setVisible(false);
        new members().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_memberActionPerformed

    private void FeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new fee().setVisible(true);
    }//GEN-LAST:event_FeeActionPerformed

    private void equipmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new product().setVisible(true);
    }//GEN-LAST:event_equipmentsActionPerformed

    private void accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        new account().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_accountActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
                new adminhome().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fee;
    private javax.swing.JButton account;
    private javax.swing.JButton equipments;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JButton member;
    // End of variables declaration//GEN-END:variables
}
