/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aumrudh Lal Kumar TJ
 */
import java.awt.Dimension;
import java.sql.*;
import javax.swing.*;
public class delfee extends javax.swing.JFrame {

    /**
     * Creates new form delfee
     */
    public final void catadd(){
    try{
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/gymautomationsystem","root","Jeyakumar28");
    PreparedStatement smt=conn.prepareStatement("Select distinct category from fee");
    ResultSet rs=smt.executeQuery();
    ccat.addItem("");
    while(rs.next()){
        String tempcat=rs.getString("category");
        ccat.addItem(tempcat);        
    }
    }       
    catch(Exception e1){
     System.out.print(e1);
    }
    }
    
    public delfee() {
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        setPreferredSize(new Dimension(500, 439));
        initComponents();
        catadd();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        delcat = new javax.swing.JButton();
        back = new javax.swing.JButton();
        ccat = new javax.swing.JComboBox<>();
        cmon = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delete Fee");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Category");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 120, 100, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Months");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 200, 80, 40);

        delcat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delcat.setText("Delete");
        delcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delcatActionPerformed(evt);
            }
        });
        getContentPane().add(delcat);
        delcat.setBounds(250, 280, 120, 50);

        back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(350, 30, 100, 40);

        ccat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(ccat);
        ccat.setBounds(200, 120, 208, 40);

        cmon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(cmon);
        cmon.setBounds(200, 200, 208, 40);

        jLabel17.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Delete Fee ");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(160, 30, 157, 41);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 280, 110, 50);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aumrudh Lal Kumar TJ\\Documents\\NetBeansProjects\\gymautotmation\\images\\gym_backgrounds_001.jpg")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 500, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void delcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delcatActionPerformed
        // TODO add your handling code here:
        String s1=(String)ccat.getSelectedItem();
        System.out.print(s1);
        String s2=(String)cmon.getSelectedItem();
        System.out.print(s2);
        try{
            if(ccat.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Select Category ","ALERT", JOptionPane.WARNING_MESSAGE);
        }
        else if(cmon.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Select Months ","ALERT", JOptionPane.WARNING_MESSAGE);
        }
        else{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/gymautomationsystem","root","Jeyakumar28");
            Statement smt=conn.createStatement();
            smt.executeUpdate("DELETE FROM fee WHERE category='"+s1+"' and Months='"+s2+"'");
            JOptionPane.showMessageDialog(null, "Deleted Sucssefully","Deletion", JOptionPane.INFORMATION_MESSAGE);
            ccat.setSelectedIndex(0);
            cmon.setSelectedIndex(0);
        }
        }
        catch(Exception e1){
            System.out.print(e1);
        }
        
    }//GEN-LAST:event_delcatActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new fee().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cmon.removeAllItems();
    try{
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/gymautomationsystem","root","Jeyakumar28");
    PreparedStatement smt=conn.prepareStatement("Select distinct Months from fee where category=?");
    String s=(String)ccat.getSelectedItem();
    smt.setString(1,s);
    ResultSet rs=smt.executeQuery();
    cmon.addItem("");    
    while(rs.next()){
        String tempcat=rs.getString("Months");
        cmon.addItem(tempcat); 
    }
    }       
    catch(Exception e1){
     System.out.print(e1);     
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(delfee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(delfee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(delfee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(delfee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new delfee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> ccat;
    private javax.swing.JComboBox<String> cmon;
    private javax.swing.JButton delcat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
