/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aumrudh Lal Kumar TJ
 */
import java.awt.Dimension;
import java.sql.*;
import javax.swing.*;
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
       setPreferredSize(new Dimension(423, 381));
       // setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sumbit = new javax.swing.JButton();
        pwd = new javax.swing.JLabel();
        passfield = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        usernametf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Login Page");
        setBackground(new java.awt.Color(102, 102, 102));
        setBounds(new java.awt.Rectangle(600, 500, 0, 0));
        getContentPane().setLayout(null);

        sumbit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        sumbit.setText("Login");
        sumbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumbitActionPerformed(evt);
            }
        });
        getContentPane().add(sumbit);
        sumbit.setBounds(80, 260, 110, 50);

        pwd.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        pwd.setText("Password");
        getContentPane().add(pwd);
        pwd.setBounds(40, 180, 110, 40);

        passfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passfieldActionPerformed(evt);
            }
        });
        getContentPane().add(passfield);
        passfield.setBounds(180, 180, 171, 40);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 260, 110, 50);

        username.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        username.setText("Username");
        getContentPane().add(username);
        username.setBounds(40, 130, 103, 28);

        usernametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametfActionPerformed(evt);
            }
        });
        getContentPane().add(usernametf);
        usernametf.setBounds(180, 130, 171, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText("  Admin  Login ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 30, 286, 49);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aumrudh Lal Kumar TJ\\Documents\\NetBeansProjects\\gymautotmation\\images\\63713515-3d-rendering-metal-dumbbell-with-gym-background.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 350);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passfieldActionPerformed

    private void sumbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumbitActionPerformed
        // TODO add your handling code here:    
            String user=usernametf.getText();
            String pass;
            pass = passfield.getText();
            if(user.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Username ","Alert",JOptionPane.WARNING_MESSAGE);
                }
             
             if(pass.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Password ","Alert",JOptionPane.WARNING_MESSAGE);
            }
             try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/gymautomationsystem","root","Jeyakumar28");
            Statement smt=conn.createStatement();
            ResultSet rs=smt.executeQuery("SELECT password FROM gym Where username='"+user+"'");            
            if(rs.next()){
                if(pass.equals(rs.getString("password"))){
                    JOptionPane.showMessageDialog(null, "Login Succesful", "Welcome " + user.toUpperCase(), JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                    new adminhome().setVisible(true);                    
                }
                else{
                    JOptionPane.showMessageDialog(null,"Invalid Password","Login Error",JOptionPane.ERROR_MESSAGE);                    
                    passfield.setText("");
                }
            }
            else{
                    JOptionPane.showMessageDialog(null,"Username not found","Login Error",JOptionPane.ERROR_MESSAGE);
                    usernametf.setText("");
                    passfield.setText("");
                }
             }
            catch(Exception e1){
     System.out.print(e1);
    }
    }//GEN-LAST:event_sumbitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usernametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametfActionPerformed
    
    public static void main(String args[]) {
                new login().setVisible(true);  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField passfield;
    private javax.swing.JLabel pwd;
    private javax.swing.JButton sumbit;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usernametf;
    // End of variables declaration//GEN-END:variables
}
