
import java.awt.Dimension;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aumrudh Lal Kumar TJ
 */
public class product extends javax.swing.JFrame {

    /**
     * Creates new form product
     */
    public product() {
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        setPreferredSize(new Dimension(871, 259));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homebutton = new javax.swing.JButton();
        addpdt = new javax.swing.JButton();
        delpdt = new javax.swing.JButton();
        viewpdt = new javax.swing.JButton();
        modpdt = new javax.swing.JButton();
        maintanence = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Product Panel");
        getContentPane().setLayout(null);

        homebutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        homebutton.setText("Back");
        homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(homebutton);
        homebutton.setBounds(723, 28, 100, 60);

        addpdt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addpdt.setText("Add ");
        addpdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpdtActionPerformed(evt);
            }
        });
        getContentPane().add(addpdt);
        addpdt.setBounds(54, 131, 123, 60);

        delpdt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delpdt.setText("Delete ");
        delpdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delpdtActionPerformed(evt);
            }
        });
        getContentPane().add(delpdt);
        delpdt.setBounds(195, 131, 115, 60);

        viewpdt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewpdt.setText("View ");
        viewpdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewpdtActionPerformed(evt);
            }
        });
        getContentPane().add(viewpdt);
        viewpdt.setBounds(328, 131, 128, 60);

        modpdt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        modpdt.setText("Modify ");
        modpdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modpdtActionPerformed(evt);
            }
        });
        getContentPane().add(modpdt);
        modpdt.setBounds(474, 131, 116, 60);

        maintanence.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        maintanence.setText("Maintainenece done ");
        maintanence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintanenceActionPerformed(evt);
            }
        });
        getContentPane().add(maintanence);
        maintanence.setBounds(602, 131, 221, 60);

        jLabel17.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Product Panel");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(310, 40, 210, 60);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aumrudh Lal Kumar TJ\\Documents\\NetBeansProjects\\gymautotmation\\images\\gym_backgrounds_001.jpg")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 870, 240);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebuttonActionPerformed
        // TODO add your handling code here:       
        new adminhome().setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_homebuttonActionPerformed

    private void delpdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delpdtActionPerformed
        // TODO add your handling code here:        
         new delpdt().setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_delpdtActionPerformed

    private void addpdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpdtActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new addpdt().setVisible(true);
    }//GEN-LAST:event_addpdtActionPerformed

    private void viewpdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewpdtActionPerformed
        // TODO add your handling code here:
                this.setVisible(false);
                new viewpdt().setVisible(true);
    }//GEN-LAST:event_viewpdtActionPerformed

    private void modpdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modpdtActionPerformed
        // TODO add your handling code here:
                this.setVisible(false);
                new updatepdt().setVisible(true);
                
    }//GEN-LAST:event_modpdtActionPerformed

    private void maintanenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintanenceActionPerformed
        // TODO add your handling code here:
               // this.setVisible(false);
                new maintainence().setVisible(true);   
                this.dispose();
    }//GEN-LAST:event_maintanenceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addpdt;
    private javax.swing.JButton delpdt;
    private javax.swing.JButton homebutton;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JButton maintanence;
    private javax.swing.JButton modpdt;
    private javax.swing.JButton viewpdt;
    // End of variables declaration//GEN-END:variables
}
