
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aumrudh Lal Kumar TJ
 */
public class saaddcustomer extends javax.swing.JFrame {

    /**
     * Creates new form saaddcustomer
     */
    public final void catadd(){
    try{
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/gymautomationsystem","root","Jeyakumar28");
    PreparedStatement smt=conn.prepareStatement("Select distinct category from fee");
    ResultSet rs=smt.executeQuery();
    feecat.addItem("");
    while(rs.next()){
        String tempcat=rs.getString("category");
        feecat.addItem(tempcat);        
    }
    }       
    catch(Exception e1){
     System.out.print(e1);
    }
    }
    public saaddcustomer() {        
        setPreferredSize(new Dimension(1050, 702));
        initComponents();
        catadd();
        feeprice.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderbuttongroup = new javax.swing.ButtonGroup();
        DOJDAY = new javax.swing.JComboBox<>();
        DOJMON = new javax.swing.JComboBox<>();
        DOJYEAR = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        DOB = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        namefield = new javax.swing.JTextField();
        DOBDAY = new javax.swing.JComboBox<>();
        DOBMONTH = new javax.swing.JComboBox<>();
        DOBYEAR = new javax.swing.JComboBox<>();
        female = new javax.swing.JRadioButton();
        weighttext = new javax.swing.JTextField();
        heighttext = new javax.swing.JTextField();
        addfield = new javax.swing.JTextField();
        mobile = new javax.swing.JLabel();
        emailid = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        feecat = new javax.swing.JComboBox<>();
        emid = new javax.swing.JTextField();
        mobileno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        adpaidtext = new javax.swing.JTextField();
        feemon = new javax.swing.JComboBox<>();
        feeprice = new javax.swing.JTextField();
        insertbutton = new javax.swing.JButton();
        home = new javax.swing.JButton();
        DOJ = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sub-Admin Add Customer");
        setMaximumSize(new java.awt.Dimension(1050, 700));
        setPreferredSize(new java.awt.Dimension(1050, 700));
        getContentPane().setLayout(null);

        DOJDAY.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DOJDAY.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        DOJDAY.setSelectedItem(null);
        getContentPane().add(DOJDAY);
        DOJDAY.setBounds(700, 83, 90, 30);

        DOJMON.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DOJMON.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        DOJMON.setSelectedItem(null);
        DOJMON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOJMONActionPerformed(evt);
            }
        });
        getContentPane().add(DOJMON);
        DOJMON.setBounds(800, 83, 90, 30);

        DOJYEAR.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DOJYEAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));
        DOJYEAR.setSelectedItem(null);
        getContentPane().add(DOJYEAR);
        DOJYEAR.setBounds(900, 83, 110, 30);

        jLabel17.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("                        Add Customer");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(230, 20, 373, 41);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 73, 120, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 130, 100, 50);

        DOB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        DOB.setForeground(new java.awt.Color(255, 255, 255));
        DOB.setText("DOB");
        getContentPane().add(DOB);
        DOB.setBounds(30, 200, 140, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 273, 140, 40);

        male.setBackground(new java.awt.Color(0, 0, 0));
        genderbuttongroup.add(male);
        male.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("Male");
        getContentPane().add(male);
        male.setBounds(190, 133, 90, 50);

        namefield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(namefield);
        namefield.setBounds(190, 73, 260, 40);

        DOBDAY.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DOBDAY.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        DOBDAY.setSelectedItem(null);
        DOBDAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBDAYActionPerformed(evt);
            }
        });
        getContentPane().add(DOBDAY);
        DOBDAY.setBounds(190, 203, 64, 30);

        DOBMONTH.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DOBMONTH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        DOBMONTH.setSelectedItem(null);
        getContentPane().add(DOBMONTH);
        DOBMONTH.setBounds(260, 203, 70, 30);

        DOBYEAR.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DOBYEAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));
        DOBYEAR.setSelectedItem(null);
        DOBYEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBYEARActionPerformed(evt);
            }
        });
        getContentPane().add(DOBYEAR);
        DOBYEAR.setBounds(340, 203, 100, 30);

        female.setBackground(new java.awt.Color(0, 0, 0));
        genderbuttongroup.add(female);
        female.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        getContentPane().add(female);
        female.setBounds(290, 133, 100, 50);

        weighttext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        weighttext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                weighttextKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                weighttextKeyTyped(evt);
            }
        });
        getContentPane().add(weighttext);
        weighttext.setBounds(700, 133, 200, 50);

        heighttext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        heighttext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                heighttextKeyTyped(evt);
            }
        });
        getContentPane().add(heighttext);
        heighttext.setBounds(700, 193, 200, 50);

        addfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addfieldActionPerformed(evt);
            }
        });
        getContentPane().add(addfield);
        addfield.setBounds(190, 273, 720, 50);

        mobile.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mobile.setForeground(new java.awt.Color(255, 255, 255));
        mobile.setText("Mobile No.");
        getContentPane().add(mobile);
        mobile.setBounds(30, 343, 180, 60);

        emailid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        emailid.setForeground(new java.awt.Color(255, 255, 255));
        emailid.setText("Email Id");
        getContentPane().add(emailid);
        emailid.setBounds(30, 423, 170, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fee Category");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 483, 160, 50);

        feecat.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(feecat);
        feecat.setBounds(200, 502, 320, 30);

        emid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emidActionPerformed(evt);
            }
        });
        getContentPane().add(emid);
        emid.setBounds(200, 413, 260, 50);

        mobileno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mobileno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilenoActionPerformed(evt);
            }
        });
        mobileno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobilenoKeyTyped(evt);
            }
        });
        getContentPane().add(mobileno);
        mobileno.setBounds(200, 353, 260, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Advance Paid");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(500, 353, 180, 50);

        adpaidtext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adpaidtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adpaidtextActionPerformed(evt);
            }
        });
        adpaidtext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                adpaidtextKeyTyped(evt);
            }
        });
        getContentPane().add(adpaidtext);
        adpaidtext.setBounds(710, 353, 200, 50);

        feemon.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        feemon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1 Month", "3 Months", "6 Months", "12 Months" }));
        feemon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                feemonItemStateChanged(evt);
            }
        });
        feemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feemonActionPerformed(evt);
            }
        });
        getContentPane().add(feemon);
        feemon.setBounds(538, 502, 150, 30);

        feeprice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(feeprice);
        feeprice.setBounds(710, 503, 110, 30);

        insertbutton.setBackground(new java.awt.Color(255, 255, 255));
        insertbutton.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        insertbutton.setText("Insert");
        insertbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(insertbutton);
        insertbutton.setBounds(310, 583, 120, 50);

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        home.setText("Back");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home);
        home.setBounds(470, 583, 120, 50);

        DOJ.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        DOJ.setForeground(new java.awt.Color(255, 255, 255));
        DOJ.setText("Date of joining");
        getContentPane().add(DOJ);
        DOJ.setBounds(490, 70, 210, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Weight");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(490, 126, 120, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Height");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(490, 193, 130, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aumrudh Lal Kumar TJ\\Documents\\NetBeansProjects\\gymautotmation\\images\\gym_backgrounds_001.jpg")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1040, 680);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DOJMONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOJMONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOJMONActionPerformed

    private void DOBDAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBDAYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBDAYActionPerformed

    private void DOBYEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBYEARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBYEARActionPerformed

    private void weighttextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_weighttextKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_weighttextKeyPressed

    private void weighttextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_weighttextKeyTyped
        // TODO add your handling code here:
        String a = weighttext.getText();
        int length = a.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if(length<3){
                weighttext.setEditable(true);
            }
            else{
                weighttext.setEditable(false);
            }
        }
        else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                weighttext.setEditable(true);
            }
            else{
                weighttext.setEditable(false);
            }
        }
    }//GEN-LAST:event_weighttextKeyTyped

    private void heighttextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_heighttextKeyTyped
        // TODO add your handling code here:
        String a = heighttext.getText();
        int length = a.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if(length<3){
                heighttext.setEditable(true);
            }
            else{
                heighttext.setEditable(false);
            }
        }
        else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                heighttext.setEditable(true);
            }
            else{
                heighttext.setEditable(false);
            }
        }
    }//GEN-LAST:event_heighttextKeyTyped

    private void addfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addfieldActionPerformed

    private void emidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emidActionPerformed

    private void mobilenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobilenoActionPerformed

    private void mobilenoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobilenoKeyTyped
        // TODO add your handling code here:
        String phone = mobileno.getText();
        int len = phone.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
            if(len<10){
                mobileno.setEditable(true);
                //JOptionPane.showMessageDialog(null, "Invalid Mobile Number","Alert", JOptionPane.WARNING_MESSAGE);
            }
            else{
                mobileno.setEditable(false);
            }
        }
        else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                mobileno.setEditable(true);
            }
            else{
                mobileno.setEditable(false);
            }
        }
    }//GEN-LAST:event_mobilenoKeyTyped

    private void adpaidtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adpaidtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adpaidtextActionPerformed

    private void adpaidtextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adpaidtextKeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE )){
            evt.consume();
        }
    }//GEN-LAST:event_adpaidtextKeyTyped

    private void feemonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_feemonItemStateChanged
        // TODO add your handling code here:
        String ctemp=(String)feecat.getSelectedItem();
        String mtemp=(String)feemon.getSelectedItem();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/gymautomationsystem","root","Jeyakumar28");
            PreparedStatement smt=conn.prepareStatement("Select price from fee where category='"+ctemp+"' and months='"+mtemp+"'");
            ResultSet rs=smt.executeQuery();
            while(rs.next()){
                String tempfee=rs.getString("price");
                feeprice.setText(tempfee);
            }
        }
        catch(Exception e1){
            System.out.print(e1);
        }
    }//GEN-LAST:event_feemonItemStateChanged

    private void feemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feemonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feemonActionPerformed

    private void insertbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbuttonActionPerformed
        // TODO add your handling code here:

        String s1=namefield.getText();
        /*if(s1.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Name","Alert",JOptionPane.WARNING_MESSAGE);
        }*/
        String s2 = null;
        if (male.isSelected())
        s2 = "MALE";
        else //if(female.isSelected())
        s2 = "FEMALE";
        /*else{
            JOptionPane.showMessageDialog(null,"Select Gender","Alert",JOptionPane.WARNING_MESSAGE);
        }*/
        String s4=(String)DOBYEAR.getSelectedItem()
        + "-" + (String)DOBMONTH.getSelectedItem()
        + "-" + (String)DOBDAY.getSelectedItem();
        String dy=(String)DOBYEAR.getSelectedItem();
        String dm=(String)DOBMONTH.getSelectedItem();
        String dd=(String)DOBDAY.getSelectedItem();
        /*if(dy == null){
            JOptionPane.showMessageDialog(null,"Select Birth Year","Alert",JOptionPane.WARNING_MESSAGE);
        }
        if(dm == null){
            JOptionPane.showMessageDialog(null,"Select Birth Month","Alert",JOptionPane.WARNING_MESSAGE);
        }
        if(dd == null){
            JOptionPane.showMessageDialog(null,"Select Birth Day","Alert",JOptionPane.WARNING_MESSAGE);
        }                */
        String s5=addfield.getText();
        /*if(s5.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Address","Alert",JOptionPane.WARNING_MESSAGE);
        }*/

        String ss6=mobileno.getText();
        //if(ss6.equals("")){
            //         JOptionPane.showMessageDialog(null,"Enter Number","Alert",JOptionPane.WARNING_MESSAGE);
            //}
        //int s6len=mobileno.getText().length();
        /*if(ss6.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Number","Alert",JOptionPane.WARNING_MESSAGE);
        }
        else if(s6len>10 ){
            JOptionPane.showMessageDialog(null, "Invalid Mobile Number","Alert", JOptionPane.WARNING_MESSAGE);
        } else if(s6len<10) {
            JOptionPane.showMessageDialog(null, "Invalid Mobile Number","Alert", JOptionPane.WARNING_MESSAGE);
        }
        else {}*/

        String s7=emid.getText();
        /*if(s7.equals("")){
            JOptionPane.showMessageDialog(null,"Enter EmailID","Alert",JOptionPane.WARNING_MESSAGE);
        }*/

        String s8=(String)DOJYEAR.getSelectedItem()+ "-" + (String)DOJMON.getSelectedItem()+"-" + (String)DOJDAY.getSelectedItem();
        String jy=(String)DOJYEAR.getSelectedItem();
        String jm=(String)DOJMON.getSelectedItem();
        String jd=(String)DOJDAY.getSelectedItem();
        /*if(jy == null){
            JOptionPane.showMessageDialog(null,"Select Joining Year","Alert",JOptionPane.WARNING_MESSAGE);
        }
        if(jm == null){
            JOptionPane.showMessageDialog(null,"Select Joining Month","Alert",JOptionPane.WARNING_MESSAGE);
        }
        if(jd == null){
            JOptionPane.showMessageDialog(null,"Select Joining Day","Alert",JOptionPane.WARNING_MESSAGE);
        }*/
        String ss9=(String)feecat.getSelectedItem();
        String st9=(String)feemon.getSelectedItem();
        String s9=(String)feecat.getSelectedItem() + "  -  " + (String)feemon.getSelectedItem();
        /*if(ss9 == null){
            JOptionPane.showMessageDialog(null,"Select Fee","Alert",JOptionPane.WARNING_MESSAGE);
        }
        if(st9 == null){
            JOptionPane.showMessageDialog(null,"Select Fee","Alert",JOptionPane.WARNING_MESSAGE);
        }*/

        String ss10=adpaidtext.getText();
        /*if(ss10.equals("")){
            JOptionPane.showMessageDialog(null, "Enter Advance Paid","Alert", JOptionPane.WARNING_MESSAGE);
        }
        else{}*/

        String ss11=weighttext.getText();
        /*if(ss11.equals("") ){
            JOptionPane.showMessageDialog(null, "Enter Weight","Alert", JOptionPane.WARNING_MESSAGE);
        }*/

        String ss12=heighttext.getText();
        /*if(ss12.equals("") ){
            JOptionPane.showMessageDialog(null, "Enter Height","Alert", JOptionPane.WARNING_MESSAGE);
        }*/

        //int s13=Integer.parseInt(ttotal.getText());

        try{
            if(s1.equals("")||s2==null||(dy == null)||(dm == null)||(dd == null)||(s5.equals(""))||(ss6.equals(""))||s7.equals("")||(ss6.equals(""))||(jy == null)||(jm == null)||(jd == null)||(ss9 == null)||(st9 == null)||ss11.equals("")||(ss10.equals(""))||(ss12.equals(""))){
                JOptionPane.showMessageDialog(null, "Enter all details ","Alert", JOptionPane.WARNING_MESSAGE);
            }
            else{
                long  s6=Long.parseLong(mobileno.getText());
                int ts9=Integer.parseInt(feeprice.getText());
                int s10= Integer.parseInt(adpaidtext.getText());
                double s11= Double.parseDouble(weighttext.getText());
                double s12= Double.parseDouble(heighttext.getText());
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/gymautomationsystem","root","Jeyakumar28");
                Statement smt=conn.createStatement();
                smt.executeUpdate("INSERT INTO CUSTOMER VALUES(NULL,'"+s1+"','"+s2+"','"+s4+"','"+s5+"',"+s6+",'"+s7+"','"+s8+"','"+s9+"',"+ts9+","+s10+","+s11+","+s12+","+s10+");");
                JOptionPane.showMessageDialog(null, "Inserted Sucssefully","Insertion", JOptionPane.INFORMATION_MESSAGE);
                //this.setVisible(false);
                namefield.setText("");
                genderbuttongroup.clearSelection();
                DOBDAY.setSelectedIndex(0);
                DOBMONTH.setSelectedIndex(0);
                DOBYEAR.setSelectedIndex(0);
                addfield.setText("");
                mobileno.setText("");
                emid.setText("");
                DOJDAY.setSelectedIndex(0);
                DOJMON.setSelectedIndex(0);
                DOJYEAR.setSelectedIndex(0);
                adpaidtext.setText("");
                weighttext.setText("");
                heighttext.setText("");
                feecat.setSelectedIndex(0);
            feemon.setSelectedIndex(0);
            feeprice.setText("");
            }
        }
        catch(Exception e1){
            JOptionPane.showMessageDialog(null, "Please enter all details","Alert", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_insertbuttonActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new subadminmembers().setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(saaddcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(saaddcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(saaddcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(saaddcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new saaddcustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DOB;
    private javax.swing.JComboBox<String> DOBDAY;
    private javax.swing.JComboBox<String> DOBMONTH;
    private javax.swing.JComboBox<String> DOBYEAR;
    private javax.swing.JLabel DOJ;
    private javax.swing.JComboBox<String> DOJDAY;
    private javax.swing.JComboBox<String> DOJMON;
    private javax.swing.JComboBox<String> DOJYEAR;
    private javax.swing.JTextField addfield;
    private javax.swing.JTextField adpaidtext;
    private javax.swing.JLabel emailid;
    private javax.swing.JTextField emid;
    private javax.swing.JComboBox<String> feecat;
    private javax.swing.JComboBox<String> feemon;
    private javax.swing.JTextField feeprice;
    private javax.swing.JRadioButton female;
    private javax.swing.ButtonGroup genderbuttongroup;
    private javax.swing.JTextField heighttext;
    private javax.swing.JButton home;
    private javax.swing.JButton insertbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton male;
    private javax.swing.JLabel mobile;
    private javax.swing.JTextField mobileno;
    private javax.swing.JTextField namefield;
    private javax.swing.JTextField weighttext;
    // End of variables declaration//GEN-END:variables
}
