
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aumrudh Lal Kumar TJ
 */
public class sadelcustomer extends javax.swing.JFrame {

    /**
     * Creates new form sadelcustomer
     */
    public final void cusadd(){
    try{
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/gymautomationsystem","root","Jeyakumar28");
    PreparedStatement smt=conn.prepareStatement("Select distinct id from customer");
    ResultSet rs=smt.executeQuery();
    tid.addItem("");    
    while(rs.next()){
        int tempcat=rs.getInt("id");
        String tcus=String.valueOf(tempcat);
        tid.addItem(tcus);        
    }
    }       
    catch(Exception e1){
     System.out.print(e1);
    }
    }
    public sadelcustomer() {
        setPreferredSize(new Dimension(468, 361));
        initComponents();
        cusadd();
        tname.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tid = new javax.swing.JComboBox<>();
        tname = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        del = new javax.swing.JButton();
        membut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sub-Admin Delete Customer");
        setMaximumSize(new java.awt.Dimension(468, 361));
        setPreferredSize(new java.awt.Dimension(468, 361));
        getContentPane().setLayout(null);

        id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setText("Id");
        getContentPane().add(id);
        id.setBounds(80, 110, 60, 50);

        jLabel17.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(" Delete Customer");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(97, 34, 233, 41);

        getContentPane().add(tid);
        tid.setBounds(193, 119, 137, 37);

        tname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnameActionPerformed(evt);
            }
        });
        getContentPane().add(tname);
        tname.setBounds(190, 190, 140, 40);

        name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Name");
        getContentPane().add(name);
        name.setBounds(70, 180, 120, 60);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(37, 265, 95, 31);

        del.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        del.setText("Delete");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        getContentPane().add(del);
        del.setBounds(164, 260, 110, 40);

        membut.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        membut.setText("Back");
        membut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                membutActionPerformed(evt);
            }
        });
        getContentPane().add(membut);
        membut.setBounds(301, 260, 120, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aumrudh Lal Kumar TJ\\Documents\\NetBeansProjects\\gymautotmation\\images\\gym_backgrounds_001.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 350);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String tempid = (String)tid.getSelectedItem();
        int tempid1=Integer.parseInt(tempid);
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/gymautomationsystem","root","Jeyakumar28");
            String sql = "Select * from customer where id = ? ";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setInt(1,tempid1);
            ResultSet rs = st.executeQuery();
            while(rs.next())
            {
                tname.setText(rs.getString("name"));
            }
            int f = 0;
            String sq = "Select id  from customer";
            PreparedStatement ps = conn.prepareStatement(sq);
            ResultSet res = ps.executeQuery();
            while(res.next())
            {
                if((tempid1 == res.getInt("id")) ){
                    f++;
                }
            }
            if(f == 1){
                //JOptionPane.showMessageDialog(null,"Doctor SSN already exists !");
                //SSN.setText("");
            }
            else{
                JOptionPane.showMessageDialog(null,"Invalid id and name !");
                tname.setText("");
            }
        }
        catch(Exception e)
        {
            System.out.print(e);

            JOptionPane.showMessageDialog(null, "No record found ","ALERT", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        String sss1=(String)tid.getSelectedItem();
        int ss1=Integer.parseInt(sss1);
        String ss2=tname.getText();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/gymautomationsystem","root","Jeyakumar28");
            Statement stmt=conn.createStatement();
            //System.out.println(s1+""+s2+""+x3+""+x4+""+s5+""+s6);
            int t=stmt.executeUpdate("DELETE FROM customer WHERE ID="+ss1+" and name='"+ss2+"'");
            if(t==0){
                JOptionPane.showMessageDialog(null, "Record not found");
            }
            else{

                tname.setText("");
                tid.setSelectedIndex(0);
                JOptionPane.showMessageDialog(null, "Deleted Succefully");
                
                this.dispose();
                new deletecustomer().setVisible(true);
                //this.setVisible(false);
            }

        }

        catch (Exception ex)  {
            System.out.println(ex);
        }
    }//GEN-LAST:event_delActionPerformed

    private void membutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new subadminmembers().setVisible(true);
    }//GEN-LAST:event_membutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sadelcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sadelcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sadelcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sadelcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sadelcustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton del;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JButton membut;
    private javax.swing.JLabel name;
    private javax.swing.JComboBox<String> tid;
    private javax.swing.JTextField tname;
    // End of variables declaration//GEN-END:variables
}
