
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aumrudh Lal Kumar TJ
 */
public class saupdatecustomer extends javax.swing.JFrame {

    /**
     * Creates new form saupdatecustomer
     */
    public final void idadd(){
    try{
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/gymautomationsystem","root","Jeyakumar28");
    PreparedStatement smt=conn.prepareStatement("Select id from customer");
    ResultSet rs=smt.executeQuery();
    id.addItem(""); 
    while(rs.next()){
        String tempcat=rs.getString("id");
        id.addItem(tempcat);        
    }
    }       
    catch(Exception e1){
     System.out.print(e1);
    }
    }
    public saupdatecustomer() {
        setPreferredSize(new Dimension(860, 600));
        initComponents();
        idadd();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modifybutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mobno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pay = new javax.swing.JTextField();
        home = new javax.swing.JButton();
        id = new javax.swing.JComboBox<>();
        tadd = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        na = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sub-Admin Update Customer");
        getContentPane().setLayout(null);

        modifybutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        modifybutton.setText("Modify");
        modifybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifybuttonActionPerformed(evt);
            }
        });
        getContentPane().add(modifybutton);
        modifybutton.setBounds(260, 430, 120, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 80, 110, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 147, 130, 60);

        mobno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mobno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobnoKeyTyped(evt);
            }
        });
        getContentPane().add(mobno);
        mobno.setBounds(285, 287, 241, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Address");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 207, 100, 60);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mobile ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 277, 90, 60);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total Payment");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 347, 140, 70);

        pay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                payKeyTyped(evt);
            }
        });
        getContentPane().add(pay);
        pay.setBounds(285, 357, 241, 40);

        home.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        home.setText("Back");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home);
        home.setBounds(680, 20, 110, 40);

        id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(id);
        id.setBounds(285, 90, 210, 40);

        tadd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(tadd);
        tadd.setBounds(285, 220, 520, 34);

        jLabel17.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(" Update Customer");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(280, 20, 300, 41);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(540, 89, 110, 40);

        na.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(na);
        na.setBounds(285, 158, 237, 39);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aumrudh Lal Kumar TJ\\Documents\\NetBeansProjects\\gymautotmation\\images\\gym_backgrounds_001.jpg")); // NOI18N
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 860, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void modifybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifybuttonActionPerformed

        String ss1=(String)id.getSelectedItem();
        String s2=na.getText();
        String s3=tadd.getText();
        String ss4=mobno.getText();
        String ss5=pay.getText();
        try{            
            if(ss1.equals("")||s3.equals("")||ss4.equals("")||ss5.equals("")){
                JOptionPane.showMessageDialog(null, "Enter all details ","Alert", JOptionPane.WARNING_MESSAGE);
            }
            else{                 
                 int s1=Integer.parseInt(ss1);
                int s5=Integer.parseInt(pay.getText());
                long  s4=Long.parseLong(mobno.getText());   
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/gymautomationsystem","root","Jeyakumar28");
            Statement smt=conn.createStatement();
            smt.executeUpdate("UPDATE CUSTOMER SET name='"+s2+"' WHERE ID="+s1+" ");
            smt.executeUpdate("UPDATE CUSTOMER SET address='"+s3+"' WHERE ID="+s1+" ");
            smt.executeUpdate("UPDATE CUSTOMER SET mobile="+s4+" WHERE ID="+s1+" ");            
            smt.executeUpdate("UPDATE CUSTOMER SET totalpaid="+s5+" WHERE ID="+s1+" ");
            JOptionPane.showMessageDialog(null, "Updated Sucssefully","Updation", JOptionPane.INFORMATION_MESSAGE);
            //this.setVisible(false);
            id.setSelectedIndex(0);
            na.setText("");
            tadd.setText("");
            mobno.setText("");
            pay.setText("");
            }
        }
        catch(Exception e1){
            System.out.print(e1);
        }
    }//GEN-LAST:event_modifybuttonActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new subadminmembers().setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String tid = (String)id.getSelectedItem();
        int tempid=Integer.parseInt(tid);
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/gymautomationsystem","root","Jeyakumar28");
            String sql = "Select * from customer where id = ? ";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setInt(1,tempid);
            ResultSet rs = st.executeQuery();
            while(rs.next())
            {
                na.setText(rs.getString("name"));
                tadd.setText(rs.getString("address"));
                mobno.setText(rs.getString("mobile"));
                pay.setText(rs.getString("totalpaid"));
            }
            int f = 0;
            String sq = "Select id , name from customer";
            PreparedStatement ps = conn.prepareStatement(sq);
            ResultSet res = ps.executeQuery();
            while(res.next())
            {
                if((tempid == res.getInt("id")) ){
                    f++;
                }
            }
            if(f == 1){
                //JOptionPane.showMessageDialog(null,"Doctor SSN already exists !");
                //SSN.setText("");
            }
            else{
                JOptionPane.showMessageDialog(null,"Invalid id and name !");
                na.setText("");
                tadd.setText("");
                mobno.setText("");
                pay.setText("");
            }
        }
        catch(Exception e)
        {
            System.out.print(e);

            JOptionPane.showMessageDialog(null, "No record found ","ALERT", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mobnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobnoKeyTyped
        // TODO add your handling code here:
        String phone = mobno.getText();
        int len = phone.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
            if(len<10){
                mobno.setEditable(true);
                //JOptionPane.showMessageDialog(null, "Invalid Mobile Number","Alert", JOptionPane.WARNING_MESSAGE);
            }
            else{
                mobno.setEditable(false);
            }
        }
        else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                mobno.setEditable(true);
            }
            else{
                mobno.setEditable(false);
            }
        }
    }//GEN-LAST:event_mobnoKeyTyped

    private void payKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_payKeyTyped
        // TODO add your handling code here:
        String phone = pay.getText();
        int len = phone.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
            if(len<10){
                pay.setEditable(true);
                //JOptionPane.showMessageDialog(null, "Invalid Mobile Number","Alert", JOptionPane.WARNING_MESSAGE);
            }
            else{
                pay.setEditable(false);
            }
        }
        else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                pay.setEditable(true);
            }
            else{
                pay.setEditable(false);
            }
        }
    }//GEN-LAST:event_payKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(saupdatecustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(saupdatecustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(saupdatecustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(saupdatecustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new saupdatecustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton home;
    private javax.swing.JComboBox<String> id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField mobno;
    private javax.swing.JButton modifybutton;
    private javax.swing.JTextField na;
    private javax.swing.JTextField pay;
    private javax.swing.JTextField tadd;
    // End of variables declaration//GEN-END:variables
}
