
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aumrudh Lal Kumar TJ
 */
public class subadminlogin extends javax.swing.JFrame {

    /**
     * Creates new form subadminlogin
     */
    public subadminlogin() {
    setPreferredSize(new Dimension(433, 369));    
    //setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userlabel = new javax.swing.JLabel();
        usernametf = new javax.swing.JTextField();
        passfield = new javax.swing.JPasswordField();
        passlabel = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sub-Admin Login");
        setMaximumSize(new java.awt.Dimension(433, 369));
        getContentPane().setLayout(null);

        userlabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        userlabel.setText("Username");
        getContentPane().add(userlabel);
        userlabel.setBounds(90, 130, 103, 28);
        getContentPane().add(usernametf);
        usernametf.setBounds(240, 120, 160, 42);
        getContentPane().add(passfield);
        passfield.setBounds(240, 180, 160, 41);

        passlabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        passlabel.setText("Password");
        getContentPane().add(passlabel);
        passlabel.setBounds(90, 180, 107, 41);

        login.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(80, 260, 120, 50);

        back.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(220, 260, 130, 50);

        jLabel18.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel18.setText("Sub-Admin Login  ");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(100, 30, 270, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aumrudh Lal Kumar TJ\\Documents\\NetBeansProjects\\gymautotmation\\images\\63713515-3d-rendering-metal-dumbbell-with-gym-background.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 430, 350);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        String user=usernametf.getText();
            String pass;
            pass = passfield.getText();
            if(user.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Username ","Alert",JOptionPane.WARNING_MESSAGE);
                }
             
             if(pass.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Password ","Alert",JOptionPane.WARNING_MESSAGE);
            }
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/gymautomationsystem","root","Jeyakumar28");
            Statement smt=conn.createStatement();
            ResultSet rs=smt.executeQuery("SELECT * FROM gymsubadmin Where username='"+user+"'");           
            if(rs.next()){
                if(pass.equals(rs.getString("password"))){
                    JOptionPane.showMessageDialog(null, "Login Succesful", "Welcome " + user.toUpperCase(), JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                    new subadminhome().setVisible(true);              
                }
                else{
                    JOptionPane.showMessageDialog(null,"Invalid Password","Login Error",JOptionPane.ERROR_MESSAGE);                    
                    passfield.setText("");
                }
            }
            else{
                    JOptionPane.showMessageDialog(null,"Username not found","Login Error",JOptionPane.ERROR_MESSAGE);
                    usernametf.setText("");
                    passfield.setText("");
                }
             }    
    catch(Exception e1){
     System.out.print(e1);
    }
    }//GEN-LAST:event_loginActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
         new home().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(subadminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(subadminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(subadminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(subadminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new subadminlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField passfield;
    private javax.swing.JLabel passlabel;
    private javax.swing.JLabel userlabel;
    private javax.swing.JTextField usernametf;
    // End of variables declaration//GEN-END:variables
}
